=begin
#TMDB API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 4

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::DefaultApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::DefaultApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultApi' do
    it 'should create an instance of DefaultApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::DefaultApi)
    end
  end

  # unit tests for account_favorite_movies
  # Favorite Movies
  # Get a user&#39;s list of favourite movies.
  # @param account_object_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [String] :language 
  # @return [AccountFavoriteMovies200Response]
  describe 'account_favorite_movies test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for account_favorite_tv
  # Favorite TV Shows
  # Get a user&#39;s list of favourite TV shows.
  # @param account_object_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [String] :language 
  # @return [AccountFavoriteTv200Response]
  describe 'account_favorite_tv test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for account_lists
  # Lists
  # Get all of the lists you&#39;ve created.
  # @param account_object_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @return [AccountLists200Response]
  describe 'account_lists test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for account_movie_recommendations
  # Recommended Movies
  # Get a user&#39;s list of recommended movies.
  # @param account_object_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [String] :language 
  # @return [AccountMovieRecommendations200Response]
  describe 'account_movie_recommendations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for account_movie_watchlist
  # Watchlist Movies
  # Get a user&#39;s movie watchlist.
  # @param account_object_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [String] :language 
  # @return [AccountMovieRecommendations200Response]
  describe 'account_movie_watchlist test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for account_rated_movies
  # Rated Movies
  # Get a user&#39;s rated movies.
  # @param account_object_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [String] :language 
  # @return [AccountRatedMovies200Response]
  describe 'account_rated_movies test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for account_rated_tv
  # Rated TV Shows
  # Get a user&#39;s rated TV shows.
  # @param account_object_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [String] :language 
  # @return [AccountRatedTv200Response]
  describe 'account_rated_tv test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for account_tv_recommendations
  # Recommended TV Shows
  # Get a user&#39;s list of recommended TV shows.
  # @param account_object_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [String] :language 
  # @return [AccountTvRecommendations200Response]
  describe 'account_tv_recommendations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for account_tv_watchlist
  # Watchlist TV Shows
  # Get a user&#39;s TV watchlist.
  # @param account_object_id 
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page 
  # @option opts [String] :language 
  # @return [AccountTvRecommendations200Response]
  describe 'account_tv_watchlist test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for auth_create_access_token
  # Create Access Token
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [AuthCreateRequestTokenRequest] :auth_create_request_token_request 
  # @return [AuthCreateAccessToken200Response]
  describe 'auth_create_access_token test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for auth_create_request_token
  # Create Request Token
  # 
  # @param [Hash] opts the optional parameters
  # @option opts [AuthCreateRequestTokenRequest] :auth_create_request_token_request 
  # @return [AuthCreateRequestToken200Response]
  describe 'auth_create_request_token test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for auth_logout
  # Logout
  # Log out of a session.
  # @param [Hash] opts the optional parameters
  # @option opts [AuthCreateRequestTokenRequest] :auth_create_request_token_request 
  # @return [AuthLogout200Response]
  describe 'auth_logout test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_clear
  # Clear
  # Clear all of the items on a list.
  # @param list_id 
  # @param [Hash] opts the optional parameters
  # @return [ListClear200Response]
  describe 'list_clear test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_create
  # Create
  # Create a new list.
  # @param [Hash] opts the optional parameters
  # @option opts [AuthCreateRequestTokenRequest] :auth_create_request_token_request 
  # @return [ListCreate200Response]
  describe 'list_create test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_delete
  # Delete
  # Delete a list.
  # @param list_id 
  # @param [Hash] opts the optional parameters
  # @return [AuthLogout200Response]
  describe 'list_delete test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_item_status
  # Item Status
  # Check if an item is on a list.
  # @param list_id 
  # @param media_id 
  # @param media_type 
  # @param [Hash] opts the optional parameters
  # @return [ListItemStatus200Response]
  describe 'list_item_status test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
