=begin
#TMDB API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 4

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::AuthCreateRequestTokenRequest
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::AuthCreateRequestTokenRequest do
  let(:instance) { OpenapiClient::AuthCreateRequestTokenRequest.new }

  describe 'test an instance of AuthCreateRequestTokenRequest' do
    it 'should create an instance of AuthCreateRequestTokenRequest' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::AuthCreateRequestTokenRequest)
    end
  end

  describe 'test attribute "raw_body"' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
