=begin
#TMDB API

#No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

The version of the OpenAPI document: 4

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 7.2.0

=end

# Common files
require 'openapi_client/api_client'
require 'openapi_client/api_error'
require 'openapi_client/version'
require 'openapi_client/configuration'

# Models
require 'openapi_client/models/account_favorite_movies200_response'
require 'openapi_client/models/account_favorite_movies200_response_results_inner'
require 'openapi_client/models/account_favorite_tv200_response'
require 'openapi_client/models/account_favorite_tv200_response_results_inner'
require 'openapi_client/models/account_lists200_response'
require 'openapi_client/models/account_lists200_response_results_inner'
require 'openapi_client/models/account_movie_recommendations200_response'
require 'openapi_client/models/account_movie_recommendations200_response_results_inner'
require 'openapi_client/models/account_rated_movies200_response'
require 'openapi_client/models/account_rated_movies200_response_results_inner'
require 'openapi_client/models/account_rated_movies200_response_results_inner_account_rating'
require 'openapi_client/models/account_rated_tv200_response'
require 'openapi_client/models/account_rated_tv200_response_results_inner'
require 'openapi_client/models/account_rated_tv200_response_results_inner_account_rating'
require 'openapi_client/models/account_tv_recommendations200_response'
require 'openapi_client/models/account_tv_recommendations200_response_results_inner'
require 'openapi_client/models/auth_create_access_token200_response'
require 'openapi_client/models/auth_create_request_token200_response'
require 'openapi_client/models/auth_create_request_token_request'
require 'openapi_client/models/auth_logout200_response'
require 'openapi_client/models/list_clear200_response'
require 'openapi_client/models/list_create200_response'
require 'openapi_client/models/list_item_status200_response'

# APIs
require 'openapi_client/api/default_api'

module OpenapiClient
  class << self
    # Customize default settings for the SDK using block.
    #   OpenapiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
